[theme]
base = "light"
primaryColor = "#018444"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F2F2"
textColor = "#383838"
borderColor = "#E3E3E3"
baseRadius = "16px"

[server]
headless = true

[browser]
gatherUsageStats = false
